/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Classes.*;
import Methods.*;
import Views.*;
import javax.swing.*;



/**
 *
 * @author andrey
 */
public class UserFrame extends javax.swing.JFrame {
        DefaultListModel<String> listModel = new DefaultListModel<>(); 
        methodsClient metClient = methodsClient.getInstance();
        methodsFriendList metFriendList = methodsFriendList.getInstance();
        methodsAddFriend metAddFriend = methodsAddFriend.getInstance();
       
        
        


    /**
     * Creates new form UserFrame
     */
    public UserFrame() {
        initComponents();
        //method to get username
         Login login = new Login();
         lblUser.setText(login.userName1);
         //method to get list name
         AddFriendList list = new AddFriendList();
         lblList.setText(list.listName);
         lblList.hide();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        bttnChange = new javax.swing.JButton();
        bttnShow = new javax.swing.JButton();
        bttnOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listClient = new javax.swing.JList<>();
        bttnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblList = new javax.swing.JLabel();
        btnSearchFriendList = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtListName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        prueba = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUser.setText("user");

        bttnChange.setText("Change data");
        bttnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnChangeActionPerformed(evt);
            }
        });

        bttnShow.setText("Show data");
        bttnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnShowActionPerformed(evt);
            }
        });

        bttnOut.setText("Log out");
        bttnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnOutActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listClient);

        bttnDelete.setText("Delete Account");
        bttnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome");

        lblList.setText("fl");

        btnSearchFriendList.setText("Search");
        btnSearchFriendList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFriendListActionPerformed(evt);
            }
        });

        jLabel2.setText("Search Friend List by Name");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("NombreLista");

        jLabel4.setText("Descrip");

        jButton3.setText("Crear lista");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Owner");

        jLabel6.setText("AñadirAmi");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bttnDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bttnOut)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblList)
                                .addGap(16, 16, 16))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtListName, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSearchFriendList, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prueba))
                            .addComponent(jButton2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttnShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnChange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnShow)
                            .addComponent(bttnChange))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtListName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchFriendList)
                        .addGap(415, 415, 415))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser)
                            .addComponent(jLabel1)
                            .addComponent(lblList))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(prueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(350, 350, 350)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnOut)
                    .addComponent(bttnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnShowActionPerformed
        //Print user data
        String user = lblUser.getText();
        Client aux = metClient.searchXUserName(user);
        PrintXData(aux);
        
    }//GEN-LAST:event_bttnShowActionPerformed

    private void bttnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnOutActionPerformed
        //exit to login frame
        Login login = new Login();
        login.show();
        this.dispose();
    }//GEN-LAST:event_bttnOutActionPerformed

    private void bttnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnChangeActionPerformed
       // go to changeData Frame
        ChangeData change = new ChangeData();
        change.show();
        this.dispose();
    }//GEN-LAST:event_bttnChangeActionPerformed

    private void bttnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeleteActionPerformed
        //delete user
        String user = lblUser.getText();
        metClient.delete(user);
        JOptionPane.showMessageDialog(null, "Deleted.");
        Login login = new Login();
        login.show();
        this.dispose();
        
    }//GEN-LAST:event_bttnDeleteActionPerformed

    private void btnSearchFriendListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFriendListActionPerformed
       String listName = txtListName.getText();
       FriendList aux = metFriendList.searchFriendlist(listName);
       listModel.clear();
        while (aux!=null) {            
            listModel.addElement("+++++++++++List++++++++++++");
            listModel.addElement("List name: "+aux.listName);
            listModel.addElement("Description: "+aux.listDescription);           
            aux = aux.next;
        }
        listClient.setModel(listModel);
        txtListName.setText("");
    }//GEN-LAST:event_btnSearchFriendListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String userName = lblUser.getText();
       String listName = lblList.getText();
        String nombre = "ClienteNombre";
        int edad = 1;
        int cedula = 1;
        boolean insertardo = metClient.InsertOrdered("b","b","b","b",2,"b","b","b","b");
        if (insertardo) {
            JOptionPane.showMessageDialog(null, "Insertado");
        }
        String nombre2 = "ClienteNombre2";
        int edad2 = 4;
        int cedula2 = 4;
        boolean insertardo2 = metClient.InsertOrdered("c","c","c","c",3,"c","c","c","c");
        if (insertardo2) {
            JOptionPane.showMessageDialog(null, "Insertado");
        }
        String nombre3 = "ProveedorNombre";
        int cedulaJuridica = 2;
        boolean insertardo3 = metClient.InsertOrdered("d","d","d","d",4,"d","d","d","d");
        if (insertardo3) {
            JOptionPane.showMessageDialog(null, "Insertado");
        }
        
        int insertardo4 = metAddFriend.insertFinal(userName,"b",listName, "Hola" );
        if (insertardo4 == 2) {
            JOptionPane.showMessageDialog(null, "OK");
        }
        
        int insertardo5 = metAddFriend.insertFinal(userName,"c",listName, "Hola");
        if (insertardo5 == 2) {
            JOptionPane.showMessageDialog(null, "OK");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //imprimir();
       // imprimir1();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String userName = jTextField3.getText();
        String friendUserName = jTextField4.getText();
        String listName = jTextField1.getText();
        String description = jTextField2.getText();
        int result = metAddFriend.insertFinal(userName, friendUserName, listName, description);
        if (result == 2) {
            JOptionPane.showMessageDialog(null, "OK");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        imprimir1(); 
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }
    //get aux from user and show data
    public void PrintXData(Client aux){
        listModel.clear();
        listModel.addElement("Name: " + aux.name );     
        listModel.addElement("Last Name: " + aux.lastName1 + " "+aux.lastName2);
        listModel.addElement("ID: " + aux.id);
        listModel.addElement("Country: "+aux.country);
        listModel.addElement("City: "+aux.city );
        listModel.addElement("Username: " + aux.userName);
        listModel.addElement("Password: " + aux.password);
        listClient.setModel(listModel);
        }
    // print List of friends
     public void printList(){
        String user = lblUser.getText();// da igual
        Client aux = metClient.searchXUserName(user);// da igual
        String listName = lblList.getText();//hay que arreglar que se meta en la sublista del usuario, imprimetodas
        FriendList auxFrnd = metFriendList.searchFriendlist(listName);
        listModel.clear();//Limpió el listModel
        while(auxFrnd!=null){
            listModel.addElement("+++++++++++List++++++++++++");
            listModel.addElement("List name: "+auxFrnd.listName);
            listModel.addElement("Description: "+auxFrnd.listDescription);           
            auxFrnd = auxFrnd.next;
        }
        listClient.setModel(listModel); 
     }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchFriendList;
    private javax.swing.JButton bttnChange;
    private javax.swing.JButton bttnDelete;
    private javax.swing.JButton bttnOut;
    private javax.swing.JButton bttnShow;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblUser;
    private javax.swing.JList<String> listClient;
    private javax.swing.JTextField prueba;
    private javax.swing.JTextField txtListName;
    // End of variables declaration//GEN-END:variables


   public void imprimir(){
        Client auxPro = metClient.head;
        listModel.clear();//Limpió el listModel
        while(auxPro!=null){
            listModel.addElement("+++++++++++++++Proveedor+++++++++");
            listModel.addElement(auxPro.userName);//Lleno el listModel
            listModel.addElement(""+auxPro.name);
            if (auxPro.sigFriendList != null) {
                listModel.addElement("Lista de Clientes****************");
                FriendList auxPC = auxPro.sigFriendList;
                while (auxPC != null) {   
                    listModel.addElement(auxPC.nextUsuario.name);
                    listModel.addElement(""+auxPC.nextUsuario.userName);
                    auxPC = auxPC.next;
                }
            }
            auxPro=auxPro.sig;
        }
        listClient.setModel(listModel);  
    }
   
public void imprimir1(){
     int cont = 1;
     methodsAddFriend newFriend = new methodsAddFriend();
     Client auxUsuario = metClient.head;
     listModel.clear();
     if (auxUsuario != null) {
         while (auxUsuario != metClient.last) {
            FriendList auxFriend = auxUsuario.sigFriendList;
             while (auxFriend != null) {
                 if (cont == 1) {
                    listModel.addElement("--------" + auxFriend.listName + "-------");
                    listModel.addElement("Owner: "+ auxUsuario.userName);
                    listModel.addElement("MemberName"+ cont +": "+ auxFriend.nextUsuario.userName);
                    cont ++;
                 }
                 else if (cont > 1) {
                     listModel.addElement("MemberName"+ cont +": "+ auxFriend.nextUsuario.userName);
                     cont ++;
                 } 
                  auxFriend = auxFriend.next;
             }
                auxUsuario = auxUsuario.next;
            }
            jList1.setModel(listModel);
        }
    }
}