/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Classes.*;
import Methods.*;
import Views.*;
import javax.swing.*;



/**
 *
 * @author andrey
 */
public class UserFrame extends javax.swing.JFrame {
        DefaultListModel<String> listModel = new DefaultListModel<>(); 
        methodsClient metClient = methodsClient.getInstance();
        methodsFriendList metFriendList = methodsFriendList.getInstance();
        methodsAddFriend metAddFriend = methodsAddFriend.getInstance();
       
        
        


    /**
     * Creates new form UserFrame
     */
    public UserFrame() {
        initComponents();
        //method to get username
         Login login = new Login();
         lblUser.setText(login.userName1);
         //method to get list name
         AddFriendList list = new AddFriendList();
         lblList.setText(list.listName);
         lblList.hide();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        bttnChange = new javax.swing.JButton();
        bttnShow = new javax.swing.JButton();
        bttnOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listClient = new javax.swing.JList<>();
        bttnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblList = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnSeeAllFriendLists = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtListName = new javax.swing.JTextField();
        btnSearchFriendList = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSeachFriend = new javax.swing.JTextField();
        btnSearchFriend = new javax.swing.JButton();
        btnSeeAllListFriendsWithTheFriends = new javax.swing.JButton();
        btnCommonFriends = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUser.setText("user");

        bttnChange.setText("Change data");
        bttnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnChangeActionPerformed(evt);
            }
        });

        bttnShow.setText("Show data");
        bttnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnShowActionPerformed(evt);
            }
        });

        bttnOut.setText("Log out");
        bttnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnOutActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listClient);

        bttnDelete.setText("Delete Account");
        bttnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome");

        lblList.setText("fl");

        jScrollPane2.setViewportView(jList1);

        jButton2.setText("Friend Lists Section");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnSeeAllFriendLists.setText("See all friend Lists");
        btnSeeAllFriendLists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeAllFriendListsActionPerformed(evt);
            }
        });

        jLabel2.setText("Search List by it's name:");

        btnSearchFriendList.setText("Search");
        btnSearchFriendList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFriendListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(txtListName, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnSearchFriendList, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnSeeAllFriendLists, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtListName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnSearchFriendList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSeeAllFriendLists)
                .addGap(20, 20, 20))
        );

        jLabel3.setText("Search Friend in the lists:");

        btnSearchFriend.setText("Search");
        btnSearchFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFriendActionPerformed(evt);
            }
        });

        btnSeeAllListFriendsWithTheFriends.setText("See all friend Lists with the friends");
        btnSeeAllListFriendsWithTheFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeAllListFriendsWithTheFriendsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(txtSeachFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnSearchFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSeeAllListFriendsWithTheFriends)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSeachFriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearchFriend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeeAllListFriendsWithTheFriends)
                .addGap(26, 26, 26))
        );

        btnCommonFriends.setText("Common Friends");
        btnCommonFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommonFriendsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bttnDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bttnOut)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblList)
                                .addGap(16, 16, 16))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCommonFriends, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bttnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttnChange)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bttnChange)
                                    .addComponent(bttnShow))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser)
                            .addComponent(jLabel1)
                            .addComponent(lblList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCommonFriends)
                        .addGap(59, 59, 59)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(418, 418, 418)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnOut)
                    .addComponent(bttnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnShowActionPerformed
        //Print user data
        String user = lblUser.getText();
        Client aux = metClient.searchXUserName(user);
        PrintXData(aux);
        
    }//GEN-LAST:event_bttnShowActionPerformed

    private void bttnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnOutActionPerformed
        //exit to login frame
        Login login = new Login();
        login.show();
        this.dispose();
    }//GEN-LAST:event_bttnOutActionPerformed

    private void bttnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnChangeActionPerformed
       // go to changeData Frame
        ChangeData change = new ChangeData();
        change.show();
        this.dispose();
    }//GEN-LAST:event_bttnChangeActionPerformed

    private void bttnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeleteActionPerformed
        //delete user
        String user = lblUser.getText();
        metClient.delete(user);
        JOptionPane.showMessageDialog(null, "Deleted.");
        Login login = new Login();
        login.show();
        this.dispose();
        
    }//GEN-LAST:event_bttnDeleteActionPerformed

    private void btnSearchFriendListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFriendListActionPerformed
       String listName = txtListName.getText();
       Client user = metClient.searchXUserName(lblUser.getText());
       FriendList aux = metFriendList.searchSpecificFriendlist(user,listName);
       listModel.clear();
        while (aux!=null) {            
            listModel.addElement("+++++++++++List++++++++++++");
            listModel.addElement("List name: "+aux.listName);
            listModel.addElement("Description: "+aux.listDescription);           
            aux = aux.next;
        }
        listClient.setModel(listModel);
        txtListName.setText("");
    }//GEN-LAST:event_btnSearchFriendListActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CreateList list = new CreateList();
        list.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSeeAllFriendListsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeAllFriendListsActionPerformed
        Client user = metClient.searchXUserName(lblUser.getText());
        printListAll(user);
        
    }//GEN-LAST:event_btnSeeAllFriendListsActionPerformed

    private void btnSearchFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFriendActionPerformed
       Client user = metClient.searchXUserName(lblUser.getText());
       String friend = txtSeachFriend.getText();
       FriendList aux = user.sigFriendList;
       listModel.clear();
        while (aux!=null) {
            if(aux.nextFriend.newFriend.userName.equals(friend) ){
            listModel.addElement("+++++++++++List++++++++++++");
            listModel.addElement("List name: "+aux.listName);
            listModel.addElement("Description: "+aux.listDescription); 
            }
            aux = aux.next;
        }
        listClient.setModel(listModel);
        txtListName.setText("");
    }//GEN-LAST:event_btnSearchFriendActionPerformed

    private void btnCommonFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommonFriendsActionPerformed
     int cont = 1;
     Client user = metClient.searchXUserName(lblUser.getText());
     Client auxUsuario = metClient.head;
     listModel.clear();
     if (auxUsuario != null) {
         while (auxUsuario != metClient.last) {
            FriendList auxFriend = auxUsuario.sigFriendList;
             while (auxFriend != null) {
                 if (cont == 1) {
                    listModel.addElement("--------" + auxFriend.listName + "-------");
                    listModel.addElement("Owner: "+ auxUsuario.userName);
                    listModel.addElement("MemberName"+ cont +": "+ auxFriend.nextFriend.newFriend.userName);
                    cont ++;
                 }
                 else if (cont > 1) {
                    listModel.addElement("MemberName"+ cont +": "+ auxFriend.nextFriend.newFriend.userName);
                     cont ++;
                 } 
                  auxFriend = auxFriend.next;
             }
                auxUsuario = auxUsuario.next;
            }
            jList1.setModel(listModel);
        }
    }//GEN-LAST:event_btnCommonFriendsActionPerformed

    private void btnSeeAllListFriendsWithTheFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeAllListFriendsWithTheFriendsActionPerformed
         Client user = metClient.searchXUserName(lblUser.getText());
        printListFriends(user);
    }//GEN-LAST:event_btnSeeAllListFriendsWithTheFriendsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }
    //get aux from user and show data
    public void imprimir4(){
    FriendList auxiliar = metFriendList.head;
    listModel.clear();
    listModel.addElement("Nombre de la lista: " + auxiliar.listName + " " + "Descripcion de la lista: " + auxiliar.listDescription);
    auxiliar = auxiliar.next;
    while (auxiliar != metFriendList.head) {
        System.out.println("Nombre de la lista: " + auxiliar.listName + " " + "Descripcion de la lista: " + auxiliar.listDescription);
        
       auxiliar = auxiliar.next;
        
    }
    
    }
    public void PrintXData(Client aux){
        listModel.clear();
        listModel.addElement("Name: " + aux.name );     
        listModel.addElement("Last Name: " + aux.lastName1 + " "+aux.lastName2);
        listModel.addElement("ID: " + aux.id);
        listModel.addElement("Country: "+aux.country);
        listModel.addElement("City: "+aux.city );
        listModel.addElement("Username: " + aux.userName);
        listModel.addElement("Password: " + aux.password);
        listClient.setModel(listModel);
        }
    // print List of friends
     public void printListFriends(Client userName){
        Client user = userName;// da igual
        FriendList auxFrnd = user.sigFriendList;
        listModel.clear();//Limpió el listModel
        while(auxFrnd!=null){
            listModel.addElement("+++++++++++List++++++++++++");
            listModel.addElement("List name: "+auxFrnd.listName);
            listModel.addElement("Description: "+auxFrnd.listDescription);           
            
            while(auxFrnd.nextFriend!=null){
            listModel.addElement(auxFrnd.nextFriend.newFriend.userName);
            listModel.addElement(auxFrnd.nextFriend.newFriend.password);
            auxFrnd.nextFriend= auxFrnd.nextFriend.sig;
            }
            auxFrnd = auxFrnd.next;
        }
        listClient.setModel(listModel); 
     }
     
     public void printListAll(Client userName){
        Client user = userName;// da igual
        FriendList auxFrnd = user.sigFriendList;
        listModel.clear();//Limpió el listModel
        while(auxFrnd!=null){
            listModel.addElement("+++++++++++List++++++++++++");
            listModel.addElement("List name: "+auxFrnd.listName);
            listModel.addElement("Description: "+auxFrnd.listDescription);           
            auxFrnd = auxFrnd.next;
        }
        listClient.setModel(listModel); 
     }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommonFriends;
    private javax.swing.JButton btnSearchFriend;
    private javax.swing.JButton btnSearchFriendList;
    private javax.swing.JButton btnSeeAllFriendLists;
    private javax.swing.JButton btnSeeAllListFriendsWithTheFriends;
    private javax.swing.JButton bttnChange;
    private javax.swing.JButton bttnDelete;
    private javax.swing.JButton bttnOut;
    private javax.swing.JButton bttnShow;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblUser;
    private javax.swing.JList<String> listClient;
    private javax.swing.JTextField txtListName;
    private javax.swing.JTextField txtSeachFriend;
    // End of variables declaration//GEN-END:variables


   public void imprimir2(){
        Client auxPro = metClient.head;
        listModel.clear();//Limpió el listModel
        while(auxPro!=null){
            listModel.addElement("+++++++++++++++Proveedor+++++++++");
            listModel.addElement(auxPro.userName);//Lleno el listModel
            listModel.addElement(""+auxPro.name);
            if (auxPro.sigFriendList != null) {
                listModel.addElement("Lista de Clientes****************");
                FriendList auxPC = auxPro.sigFriendList;
                while (auxPC != null) {   
//                    listModel.addElement(auxPC.nextUsuario.name);
                 //   listModel.addElement(""+auxPC.nextUsuario.userName);
                    auxPC = auxPC.next;
                }
            }
            auxPro=auxPro.sig;
        }
        listClient.setModel(listModel);  
    }
   
public void imprimir1(){
     int cont = 1;
     methodsAddFriend newFriend = new methodsAddFriend();
     Client auxUsuario = metClient.head;
     listModel.clear();
     if (auxUsuario != null) {
         while (auxUsuario != metClient.last) {
            FriendList auxFriend = auxUsuario.sigFriendList;
             while (auxFriend != null) {
                 if (cont == 1) {
                    listModel.addElement("--------" + auxFriend.listName + "-------");
                    listModel.addElement("Owner: "+ auxUsuario.userName);
                 //   listModel.addElement("MemberName"+ cont +": "+ auxFriend.nextUsuario.userName);
                    cont ++;
                 }
                 else if (cont > 1) {
                  //   listModel.addElement("MemberName"+ cont +": "+ auxFriend.nextUsuario.userName);
                     cont ++;
                 } 
                  auxFriend = auxFriend.next;
             }
                auxUsuario = auxUsuario.next;
            }
            jList1.setModel(listModel);
        }
    }
 public void PrintAllUsers(Client aux){
        listModel.clear();
        listModel.addElement("UserName:" + aux.userName);
        listModel.addElement("ID" + aux.id);
        aux=aux.next;

        while(aux!=metClient.head){
            listModel.addElement("UserName: " + aux.userName);
            listModel.addElement("ID: " + aux.id);
            aux=aux.next;
        }
        
        jList1.setModel(listModel);
        
        }
}